### ISSUE TITLE
评论和访问者不显示

### ISSUE THREAD

**Issue by ghost** [waylau/jekyll-bootstrap-blog#4]
把作者的模板重新部署到Github发现 Latest Comments 和 Recently Visitors 不起作用，而且每一篇博客的文章也不能评论了。

**Comment by waylau** [comment]
@shenwiyn   你所部署的网站，是使用了  https  协议了吗？？

**Comment by ghost** [comment]
嗯嗯，ok了，更新一下多说插件的代码后，Recently Visitors 可以用了。
@waylau 博主的博客很强大，赞一个！
